# Generated by Django 4.2.5 on 2023-09-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusic', '0002_instrumentos_delete_intrumentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='categoria',
            field=models.CharField(choices=[('BATERIA', 'Bateria'), ('CORDAS', 'Cordas'), ('ELETRONICO', 'Eletronico'), ('METAIS', 'Metais'), ('PERCUSAO', 'Percusao'), ('SOPRO', 'Sopro'), ('TECLAS', 'Teclas'), ('ACESSORIOS', 'Acessorios')], max_length=15),
        ),
    ]
